/**
 * Catalogue mirroring the storefront of riogiftshop.com: the same category
 * tree, product names, slugs and price points, re-skinned for ZED Gift Shop 2.
 */

export type RioCategory = {
  slug: string;
  name: string;
  children?: { slug: string; name: string }[];
};

export const RIO_CATEGORIES: RioCategory[] = [
  {
    slug: "men-gifts",
    name: "Men",
    children: [
      { slug: "birthday-gifts", name: "Birthday Gifts for Him" },
      { slug: "birthday-gift-shop-in-nairobi", name: "Birthday Gift Shop in Nairobi" },
      { slug: "secret-santa-gifts", name: "Men Secret Santa Gifts" },
      { slug: "gift-for-dad", name: "Gift for Dad" },
      { slug: "gift-for-boss", name: "Gift for Boss" },
      { slug: "romantic-gifts", name: "Men Romantic Gifts" },
      { slug: "wedding-gifts", name: "Men Wedding Gifts" },
      { slug: "graduation-gifts", name: "Men Graduation Gifts" },
      { slug: "anniversary-gifts", name: "Men Anniversary Gifts" },
      { slug: "just-because-gifts", name: "Men Just Because Gifts" },
      { slug: "fathers-day-gifts", name: "Father's Day Gifts" },
      { slug: "valentines-day-gifts", name: "Valentine's Day Gifts" },
      { slug: "mens-watches", name: "Mens Watches" },
      { slug: "men-name-tags", name: "Men Name Tags" },
      { slug: "desk-organizers", name: "Desk Organizers" },
      { slug: "hip-flask-gift-set", name: "Hip Flask Gift Set" },
      { slug: "mens-leather-wallets", name: "Mens Leather Wallets" },
      { slug: "tie-clips", name: "Tie Clips" },
      { slug: "best-perfumes", name: "Best Perfumes in Nairobi" },
      { slug: "cufflinks", name: "Cufflinks" },
      { slug: "mens-socks", name: "Mens Socks" },
    ],
  },
  {
    slug: "ladies-gifts",
    name: "Women",
    children: [
      { slug: "ladies-secret-santa", name: "Ladies Secret Santa" },
      { slug: "women-gifts-for-boss", name: "Women Gifts for Boss" },
      { slug: "ladies-gifts-for-mom", name: "Ladies Gifts for Mom" },
      { slug: "ladies-romantic-gifts", name: "Ladies Romantic Gifts" },
      { slug: "ladies-graduation-gifts", name: "Ladies Graduation Gifts" },
      { slug: "ladies-anniversary-gifts", name: "Anniversary Gifts in Nairobi" },
      { slug: "just-because-gifts-for-her", name: "Just Because Gifts for Her" },
      { slug: "valentines-day-gifts-for-her", name: "Valentines Day Gifts for Her" },
      { slug: "birthday-gifts-for-her", name: "Birthday Gifts For Her" },
      { slug: "ladies-watch-organizer", name: "Ladies Watch Organizer" },
      { slug: "ladies-clutch-bags", name: "Ladies Clutch Bags" },
      { slug: "ladies-giftsets", name: "Ladies Giftsets" },
      { slug: "hair-straightener", name: "Hair Straightener" },
      { slug: "perfumes-for-women", name: "Perfumes for Women" },
      { slug: "ladies-card-holders", name: "Ladies Card Holders" },
      { slug: "ladies-name-tags", name: "Ladies Name Tags" },
      { slug: "i-love-cosmetics", name: "I Love Cosmetics" },
    ],
  },
  {
    slug: "corporate-gifts-kenya",
    name: "Corporate Gifts",
    children: [
      { slug: "corporate-gifts-ideas", name: "Corporate Gifts Ideas" },
      { slug: "executive-corporate-gifts", name: "Executive Corporate Gifts" },
      { slug: "corporate-gift-sets", name: "Corporate Gift Sets" },
      { slug: "2026-diary", name: "2026 Diary" },
      { slug: "2027-diaries", name: "2027 Diaries" },
      { slug: "schools-awards", name: "For Schools" },
      { slug: "individuals-awards", name: "For Individuals" },
      { slug: "companies-awards", name: "For Companies" },
      { slug: "power-banks", name: "Power Banks" },
      { slug: "tumbler", name: "Tumblers" },
      { slug: "jute-tote-bags", name: "Jute Tote Bags" },
      { slug: "thermal-flasks", name: "Thermal Flasks" },
    ],
  },
  {
    slug: "promotional-gifts",
    name: "Promotional Gifts",
    children: [
      { slug: "mug-printing", name: "Mug Printing in Nairobi" },
      { slug: "thermo-mugs", name: "Thermo Mugs in Kenya" },
      { slug: "water-bottles", name: "Water Bottles" },
      { slug: "crystal-items", name: "Crystal Items" },
      { slug: "keychain", name: "Keychain" },
      { slug: "tie-sets", name: "Tie Sets" },
      { slug: "leather-belts", name: "Leather Belts" },
      { slug: "leather-wallets", name: "Leather Wallets" },
      { slug: "customized-notebooks", name: "Customized Notebooks & Journals" },
      { slug: "branded-executive-pens", name: "Branded Executive Pens in Nairobi" },
      { slug: "wooden-products", name: "Wooden Products in Nairobi" },
    ],
  },
  {
    slug: "personalized-gifts",
    name: "Personalized Gifts",
    children: [
      { slug: "stanley-inspired-cups", name: "Stanley Inspired Cups" },
      { slug: "thermal-mugs", name: "Thermal Mugs" },
      { slug: "uv-printed-mugs", name: "UV Printed Mugs" },
      { slug: "uv-printed-keychain", name: "UV Printed Keychain" },
      { slug: "uv-printed-name-tags", name: "UV Printed Name Tags" },
      { slug: "digital-printed-mugs", name: "Digital Printed Mugs" },
      { slug: "digital-printed-keychain", name: "Digital Printed Keychain" },
      { slug: "digital-printed-name-tags", name: "Digital Printed Name Tags" },
      { slug: "sublimation-mugs", name: "Sublimation Mugs" },
      { slug: "sublimation-bottles", name: "Sublimation Water Bottles" },
    ],
  },
  {
    slug: "men-watches-on-sale",
    name: "Watches",
    children: [
      { slug: "kids-watches", name: "Kids Watches" },
      { slug: "smart-watches", name: "Smart Watches" },
    ],
  },
  {
    slug: "mens-watches",
    name: "Men By Brand",
    children: [
      { slug: "curren", name: "Curren" },
      { slug: "olevs", name: "Olevs" },
      { slug: "crrju", name: "Crrju" },
      { slug: "chenxi", name: "Chenxi" },
      { slug: "poedagar", name: "Poedagar" },
      { slug: "skmei", name: "Skmei" },
      { slug: "lige", name: "Lige" },
      { slug: "naviforce", name: "Naviforce" },
      { slug: "forsining", name: "Forsining" },
      { slug: "fngreen", name: "Fngreen" },
      { slug: "sanda", name: "Sanda" },
      { slug: "wwoor", name: "Wwoor" },
      { slug: "automatic-watches", name: "Automatic Watches" },
      { slug: "jesou-collection", name: "Jesou Collection" },
    ],
  },
  {
    slug: "ladies-watches",
    name: "Ladies By Brand",
    children: [
      { slug: "gift-set-watches", name: "Gift Set Watches" },
    ],
  },
  { slug: "couple-watches", name: "Couple Watches", children: [{ slug: "his-and-hers", name: "His & Hers Sets" }] },
  {
    slug: "pendant-necklaces",
    name: "Jewerly",
    children: [
      { slug: "necklaces", name: "Necklaces in Nairobi" },
      { slug: "earrings", name: "Earrings in Nairobi" },
      { slug: "rings", name: "Rings in Nairobi" },
      { slug: "matching-jewellery-sets", name: "Matching Jewellery Sets" },
      { slug: "valentines-necklaces", name: "Valentines Day Necklaces" },
      { slug: "couple-necklaces", name: "Couple Necklaces" },
    ],
  },
  {
    slug: "kenya-bracelets",
    name: "Bracelets",
    children: [
      { slug: "men-bracelets", name: "Men Bracelets" },
      { slug: "bracelets-for-women", name: "Bracelets for Women" },
    ],
  },
  {
    slug: "shoes-for-men",
    name: "Shoes",
    children: [
      { slug: "mens-loafers", name: "Mens Loafers & Slip Ons" },
      { slug: "men-sneakers", name: "Men Sneakers on Sale" },
      { slug: "official-shoes", name: "Mens Official Shoes Kenya" },
      { slug: "ladies-loafers", name: "Womens Loafers in Nairobi" },
    ],
  },
  { slug: "award-trophies-in-nairobi", name: "Trophies" },
  { slug: "branded-trophies-in-nairobi", name: "Branded Trophies in Nairobi" },
  { slug: "maasai-blankets-in-nairobi", name: "Maasai Blankets in Kenya" },
  { slug: "kenya-inspired-blankets", name: "Kenya Inspired Blankets" },
  { slug: "desk-organizers-in-nairobi", name: "Desk Organizers in Nairobi" },
  { slug: "watch-organizer", name: "Watch Organizers" },
  { slug: "keychains", name: "Keychains" },
  { slug: "card-holder-wallet", name: "Card Holder Wallets" },
  { slug: "wholesale", name: "Wholesale" },
];

export type RioProduct = {
  slug: string;
  name: string;
  price: number;
  compareAtPrice?: number;
  categories: string[];
  tags?: string[];
  featured?: boolean;
  bestSeller?: boolean;
  personalizationEnabled?: boolean;
  giftWrapAvailable?: boolean;
  quantity?: number;
  shortDescription: string;
  description: string;
};

const BLANKET_COPY =
  "Woven Maasai-inspired shuka in a heavyweight fleece, finished with a hand-tied edge and fringe. A warm, genuinely useful gift that suits a house, a farm, or a very good friend. Available in a range of colours.";

const BULK_NOTE = "Bulk and repeat orders available on request — just add your quantity at checkout.";

function p(
  slug: string,
  name: string,
  price: number,
  compareAtPrice: number | undefined,
  categories: string[],
  shortDescription: string,
  description: string,
  extra: Partial<RioProduct> = {},
): RioProduct {
  return {
    slug,
    name,
    price,
    compareAtPrice,
    categories,
    shortDescription,
    description,
    quantity: 60,
    giftWrapAvailable: true,
    ...extra,
  };
}

export const RIO_PRODUCTS: RioProduct[] = [
  // ---------- Featured (homepage "Featured Categories") ----------
  p("embroidered-fleece-blanket-in-kenya", "Branded Maasai Shuka with Heavy Fleece Blanket", 3499, 4000,
    ["maasai-blankets-in-nairobi", "corporate-gifts-kenya", "kenya-inspired-blankets", "for-him"],
    "Maasai shuka with an added heavy fleece layer and room for your logo.",
    `${BLANKET_COPY} We can embroider your logo or a short message onto the fleece panel. ${BULK_NOTE}`,
    { featured: true, tags: ["maasai", "blanket", "corporate"], personalizationEnabled: true }),
  p("high-quality-engraved-beer-mugs", "Personalized Engraved Glass Beer Mug", 1499, 2000,
    ["promotional-gifts", "mug-printing", "personalized-gifts", "for-him"],
    "Heavy glass mug with a laser-engraved name — built to survive parties.",
    "Thick-walled beer mug with a solid handle and a laser-engraved name, title or date. Engraving is permanent and will not wash off. Priced for teams of ten and up.",
    { featured: true, tags: ["mug", "engraving"], personalizationEnabled: true }),
  p("high-end-corporate-gift-hampers", "High-End Branded Corporate Gift Hamper", 6499, 7000,
    ["corporate-gifts-kenya", "corporate-gift-sets", "executive-corporate-gifts"],
    "A premium hamper built for client gifting and executive rewards.",
    "A boxed hamper pairing a stainless steel drinkware set, an executive diary, a quality pen and a soft-touch card, all branded with your logo and wrapped in a rigid gift box with a handwritten card.",
    { featured: true, tags: ["corporate", "hamper"] }),
  p("company-branded-merchandise", "Personalized Corporate Gift Set - Notebook, Tumbler, Tote Bag & Pen", 4999, 6500,
    ["corporate-gifts-kenya", "corporate-gift-sets", "jute-tote-bags", "tumbler"],
    "Four branded pieces in one box — notebook, tumbler, tote bag and pen.",
    "Everything a team actually uses: an A5 notebook, a 500ml tumbler, a reusable jute tote bag and a metal executive pen, all printed with your logo and packed in a gift box with a card.",
    { featured: true, tags: ["corporate", "set"] }),
  p("ultimate-fleece-maasai-shuka-blanket", "Ultimate Fleece Maasai Shuka Blanket", 3499, 4000,
    ["maasai-blankets-in-nairobi", "kenya-inspired-blankets", "for-him", "corporate-gifts-kenya"],
    "Our heaviest shuka yet — double-sided fleece and a proper hem.",
    "The blanket we send most often. Double-sided fleece, a reinforced hem and the classic Maasai stripe. Warm enough for the highlands and handsome enough to keep on a sofa.",
    { featured: true, tags: ["maasai", "blanket"] }),
  p("personalized-business-gift-sets", "Custom Corporate Gift Set with Branded Tote Bag, Tumbler, Notebook, Pen & Desk Organizer", 6499, 7000,
    ["corporate-gifts-kenya", "corporate-gift-sets", "executive-corporate-gifts", "desk-organizers-in-nairobi"],
    "Five pieces, one box — the full branded desk-and-bag set.",
    "Our most complete corporate set: branded tote bag, tumbler, notebook, executive pen and a wooden desk organizer, printed to your specification and packed with a card.",
    { featured: true, tags: ["corporate", "set"] }),
  p("maasai-heritage-fleece-blanket", "Maasai Heritage Fleece Blanket", 3499, 4000,
    ["maasai-blankets-in-nairobi", "kenya-inspired-blankets", "corporate-gifts-kenya"],
    "Heritage stripe in a soft fleece weave, trimmed by hand.",
    "A heritage-weight Maasai shuka in soft fleece, hand-trimmed with a traditional fringe. A souvenir that is also the gift people use every evening.",
    { featured: true, tags: ["maasai", "blanket"] }),
  p("personalized-blue-gift-set", "Personalized Blue Gift Set with Tumbler, Notebook, Pen & Keychain", 3799, 4500,
    ["corporate-gifts-kenya", "corporate-gift-sets", "tumbler", "keychain"],
    "Four coordinated pieces in a deep blue gift box.",
    "A 500ml tumbler, A5 notebook, executive pen and keychain in a matching deep blue, each printed with your logo and boxed together with a card.",
    { featured: true, tags: ["corporate", "set", "blue"] }),
  p("custom-logo-jute-tote-bags", "Reusable Corporate Shopping Gift Bags", 1299, 1500,
    ["corporate-gifts-kenya", "jute-tote-bags", "promotional-gifts"],
    "Sturdy reusable jute totes with your logo printed on the front.",
    "Heavy natural jute totes with reinforced handles and a screen-printed logo. They survive the supermarket run and the good-news run. Available in A3, A4 and A5 sizes.",
    { featured: true, tags: ["jute", "tote", "corporate"] }),
  p("long-lasting-female-arabian-perfume-spray", "Lattafa Yara Elixir Eau de Parfum for Women 100ml", 3299, 3500,
    ["ladies-gifts", "perfumes-for-women", "for-her"],
    "A long-wearing oriental floral fragrance in a 100ml bottle.",
    "Yara Elixir opens with top notes of mandarin and bergamot over a heart of rose and jasmine, settling into amber and vanilla. A serious 100ml bottle that lasts all day.",
    { featured: true, tags: ["perfume", "women"] }),

  // ---------- Best selling ----------
  p("employee-name-tags", "Branded Gold Acrylic Name Tag", 499, 800,
    ["corporate-gifts-kenya", "men-name-tags", "promotional-gifts", "personalized-gifts"],
    "Gold acrylic name tags, printed with the name and role you choose.",
    "Polished gold acrylic name tags with a safety pin or lanyard attachment. Send us a list of names and titles and we will print them. Order by the dozen for your team or event.",
    { bestSeller: true, personalizationEnabled: true, tags: ["name-tag", "corporate", "acrylic"] }),
  p("multi-colour-diary-2027", "Premium B5 Executive Diaries", 1799, 2000,
    ["corporate-gifts-kenya", "2027-diaries", "promotional-gifts"],
    "B5 executive diaries in a range of colours, branded on the cover.",
    "A5-to-B5 executive diary with a hard cover, ribbon marker, pen loop and a full year of undated spreads. Your logo foil-stamped on the cover in any of six colours.",
    { bestSeller: true, tags: ["diary", "2027", "executive"] }),
  p("promotional-drink-water-bottles", "Branded Mixed-Colour Skin Feel Thermal Flasks – 500ml", 1499, 2000,
    ["promotional-gifts", "water-bottles", "corporate-gifts-kenya", "thermal-flasks"],
    "Soft-touch 500ml flasks in assorted colours, printed with your logo.",
    "Double-walled stainless steel flasks with a skin-feel soft-touch coating, in a range of mixed colours. UV printed with your logo or a name, so the print will not crack.",
    { bestSeller: true, personalizationEnabled: true, tags: ["flask", "bottle", "drinkware"] }),
  p("arabic-perfumes-for-women", "Elegant Floral Fruity Perfume for Women", 3499, 4000,
    ["ladies-gifts", "perfumes-for-women", "for-her"],
    "A floral-fruity eau de parfum that people comment on.",
    "A bright floral-fruity opening over a soft amber base, in a 100ml bottle with a clean weighted cap. One of our most repurchased fragrances.",
    { bestSeller: true, tags: ["perfume", "women"] }),
  p("2027-diaries-and-organizers", "Premium Business Maroon 2027 Diary – A5", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries", "2026-diary"],
    "Maroon A5 diary with a week-to-view layout and a pen loop.",
    "A hardback A5 business diary in maroon with a week-to-view layout, gilt-edged pages, a ribbon marker and a pen loop. Branded on the cover in white or gold.",
    { bestSeller: true, tags: ["diary", "2027"] }),
  p("branded-2027-diaries-at-rio-gift-shop", "Branded 2027 Executive Diary – A4", 1999, 2500,
    ["corporate-gifts-kenya", "2027-diaries", "executive-corporate-gifts"],
    "A4 executive diary — the size that sits on a desk and gets used.",
    "A generous A4 executive diary with monthly planning pages, notes sections and a hard cover. A long-lasting corporate gift that will not end up in a drawer.",
    { bestSeller: true, tags: ["diary", "2027", "executive"] }),

  // ---------- Main catalogue grid ----------
  p("premium-black-and-brown-belts", "Double-Sided Black & Brown Formal Belt", 2499, 3000,
    ["promotional-gifts", "leather-belts", "men-gifts", "for-him"],
    "Reversible formal belt with a reversible buckle and gift box.",
    "A double-sided belt in black and brown with a reversible buckle, genuine leather and a 3.5cm width. Supplied in a gift box — engraving available on the buckle.",
    { personalizationEnabled: true, tags: ["belt", "leather", "formal"] }),
  p("branded-skin-feel-thermal-flasks", "Premium Personalized Insulated Skin Feel Water Bottles – 500ml", 1499, 1800,
    ["promotional-gifts", "water-bottles", "personalized-gifts", "sublimation-bottles"],
    "Insulated soft-touch bottles, printed with a name or a photo.",
    "500ml double-walled stainless steel bottles with a skin-feel finish. Print a name, a date or a photograph across the body — ideal for weddings and team events.",
    { personalizationEnabled: true, tags: ["flask", "personalized", "drinkware"] }),
  p("genuine-leather-bifold-wallets", "Men's Premium Genuine Leather Bifold Wallet", 2000, 2500,
    ["promotional-gifts", "leather-wallets", "men-gifts", "mens-leather-wallets"],
    "Full-grain leather bifold with six card slots and a note pocket.",
    "A slim bifold in genuine full-grain leather with six card slots, two note compartments and an ID window. Monogrammed free of charge if you tell us the initials.",
    { personalizationEnabled: true, tags: ["wallet", "leather", "men"] }),
  p("reusable-jute-shopping-bag", "Blue Handle Reusable Shopping Jute Bag", 1299, 1500,
    ["corporate-gifts-kenya", "jute-tote-bags", "promotional-gifts"],
    "Reusable jute shopping bag with contrast handles and a print area.",
    "A sturdy reusable jute bag with reinforced contrast handles and a generous print area for your logo. Folds flat for shipping, holds a lot once it arrives.",
    { tags: ["jute", "tote"] }),
  p("corporate-gift-water-bottles", "Personalized Black 500ml Soft-Touch Thermal Flask", 1499, 1800,
    ["corporate-gifts-kenya", "thermal-flasks", "personalized-gifts"],
    "Matte black soft-touch flask with a laser-etched name.",
    "A 500ml flask in matte black with a soft-touch coating, laser-etched with a name, a logo or a short message. Six hours hot, twelve cold.",
    { personalizationEnabled: true, tags: ["flask", "black", "personalized"] }),
  p("kenyan-souvenirs-and-corporate-gifts", "Kenya Jute Tote Bag & Maasai-Inspired Fleece Blanket Gift Set", 4499, 5000,
    ["maasai-blankets-in-nairobi", "corporate-gifts-kenya", "jute-tote-bags", "kenya-inspired-blankets"],
    "Jute tote and fleece blanket boxed together — our Kenya souvenir set.",
    "The pairing customers order most: a reusable jute tote bag and a Maasai-inspired fleece blanket, boxed together with a card. A natural gift for anyone who has not been to Kenya yet.",
    { tags: ["set", "maasai", "jute"] }),
  p("vibrant-kenyan-gift-set", "Yellow Jute Tote Bag & Maasai-Inspired Fleece Blanket Gift Set", 4499, 5000,
    ["maasai-blankets-in-nairobi", "kenya-inspired-blankets", "jute-tote-bags"],
    "The Kenya set in a warm yellow weave.",
    "Same great pairing in a bright yellow weave: a reusable jute tote and a Maasai-inspired fleece blanket, boxed with a card and a ribbon.",
    { tags: ["set", "maasai", "jute"] }),
  p("jute-tote-bag-and-fleece-blanket-set", "A3 Jute Tote Bag & Maasai-Inspired Fleece Blanket", 4499, 5000,
    ["maasai-blankets-in-nairobi", "jute-tote-bags", "kenya-inspired-blankets"],
    "The larger A3 size of our most-ordered gift set.",
    "An oversized A3 jute tote paired with a Maasai-inspired fleece blanket. Chosen when the gift has to look generous from across the room.",
    { tags: ["set", "maasai", "jute"] }),
  p("2027-diaries-personalized-by-rio-gift-shop", "Personalized Red 2027 Executive Diary & Pen Gift Set", 2000, 2500,
    ["corporate-gifts-kenya", "2027-diaries", "branded-executive-pens"],
    "A red executive diary paired with a matching metal pen.",
    "A red A5 executive diary and a matching metal pen, presented in a gift box. A classic combination for staff gifting and end-of-year rewards.",
    { tags: ["diary", "pen", "set", "2027"] }),
  p("corporate-diaries-2027", "2027 Premium Executive Diary & Pen Gift Set", 2000, 2500,
    ["corporate-gifts-kenya", "2027-diaries", "branded-executive-pens"],
    "Premium diary and pen set for 2027, boxed and branded.",
    "A premium executive diary and metal pen in a presentation box, ready to hand out. Branded on the cover and sleeve for your organisation.",
    { tags: ["diary", "pen", "set"] }),
  p("business-planner-2027", "Premium Black 2027 A5 Diary", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries", "2026-diary"],
    "Understated black A5 planner with gilt edges.",
    "A hardback A5 planner in black with gilt-edged pages, a week-to-view layout and a ribbon marker. Branded in white, silver or gold.",
    { tags: ["diary", "planner", "2027"] }),
  p("best-diaries-for-2027-in-kenya", "2027 Royal Blue Executive Diary – A5", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries"],
    "Royal blue A5 executive diary for 2027.",
    "A royal blue hardback A5 diary with a week-to-view layout, a pen loop and a ribbon marker. A corporate favourite for year-end gifting.",
    { tags: ["diary", "2027", "blue"] }),
  p("a5-executive-diaries-2027", "Black A5 2027 Executive Diary", 1299, 1800,
    ["corporate-gifts-kenya", "2027-diaries"],
    "Compact black A5 executive diary.",
    "A pocket-friendly A5 executive diary in black, with quarterly planning pages and a hard cover that survives a bag.",
    { tags: ["diary", "2027", "black"] }),
  p("executive-2027-diaries", "Personalized 2027 Executive Diary – A5", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries", "personalized-gifts"],
    "A5 diary with a name or initials foil-stamped on the cover.",
    "A hardback A5 executive diary, personalised with a name, initials or a short message on the cover. We will send a proof before we print the batch.",
    { personalizationEnabled: true, tags: ["diary", "personalized", "2027"] }),
  p("a4-executive-diaries-2027", "Premium 2027 Executive Diary – A4", 1999, 2500,
    ["corporate-gifts-kenya", "2027-diaries", "executive-corporate-gifts"],
    "Desk-sized A4 executive diary with planning sections.",
    "A large-format A4 executive diary with dedicated goal and planning pages, a hard cover and a ribbon marker. Designed to be left open on a desk.",
    { tags: ["diary", "2027", "a4"] }),
  p("2027-diaries-and-calendars", "Premium Executive 2027 B5 Diaries", 1800, 2000,
    ["corporate-gifts-kenya", "2027-diaries"],
    "B5 executive diaries at our volume price.",
    "B5 executive diaries with a soft-touch cover, a pen loop and a full year of planning pages. The size teams usually ask for, at the price that makes bulk work.",
    { tags: ["diary", "2027", "b5"] }),
  p("premium-2027-executive-diaries-a5", "Premium 2027 Executive Diaries – A5", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries"],
    "A5 executive diaries in a soft-touch premium finish.",
    "Premium A5 executive diaries with a soft-touch cover, gilt-edged pages and a ribbon marker. Our most reliable repeat order for corporate gifting.",
    { tags: ["diary", "2027", "a5"] }),
  p("a5-2027-premium-executive-diaries", "A5 2027 Premium Executive Diaries", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries"],
    "A5 premium diaries, ready to brand in bulk.",
    "A5 premium executive diaries with a hard cover and a full year of spreads. Send us your list of names and we will brand every copy.",
    { personalizationEnabled: true, tags: ["diary", "2027", "bulk"] }),
  p("personalized-a5-2027-diary", "Elegant A5 Green 2027 Diary", 1300, 1800,
    ["corporate-gifts-kenya", "2027-diaries", "personalized-gifts"],
    "Green A5 diary with a name printed on the front.",
    "A deep green A5 diary with a name or initials printed on the cover, a week-to-view layout and a ribbon marker.",
    { personalizationEnabled: true, tags: ["diary", "green", "2027"] }),
  p("luxury-floral-fruity-perfume-lattafa-habik", "Lattafa Habik For Women Eau de Parfum 100ml", 3499, 4000,
    ["ladies-gifts", "perfumes-for-women", "for-her"],
    "A warm oriental fragrance for women, 100ml.",
    "Habik pairs a sweet oriental base with a bright citrus opening and a floral heart. A 100ml bottle with a long drydown — the one we restock most often.",
    { tags: ["perfume", "women"] }),
  p("personalized-executive-desk-organizer", "Personalized Black Wooden Digital Desk Organizer", 2499, 3000,
    ["desk-organizers-in-nairobi", "corporate-gifts-kenya", "personalized-gifts", "promotional-gifts"],
    "A black wooden desk organizer with your logo laser-etched.",
    "A compartmented wooden desk organizer in a matte black finish, laser-etched with your logo or a name. Holds a phone, a pen, cards and a notebook.",
    { personalizationEnabled: true, tags: ["desk", "wooden", "personalized"] }),
  p("perpetual-desk-calendar", "Personalized Wooden Perpetual Desk Calendar", 2499, 3000,
    ["desk-organizers-in-nairobi", "corporate-gifts-kenya", "promotional-gifts"],
    "A perpetual wooden calendar you never have to replace.",
    "A wooden perpetual desk calendar with interchangeable blocks and a laser-etched name or logo on the base. A gift that stays on the desk for years.",
    { personalizationEnabled: true, tags: ["desk", "calendar", "wooden"] }),
  p("maasai-blankets-in-kenya", "Custom Embroidered Corporate, Appreciation & Celebration Gift", 3499, 4000,
    ["maasai-blankets-in-nairobi", "corporate-gifts-kenya", "kenya-inspired-blankets", "for-him"],
    "A Maasai blanket embroidered for appreciation, celebration or corporate use.",
    "A Maasai-inspired fleece blanket with your logo, a message or a name embroidered onto the panel. Our most requested corporate blanket for staff recognition and client gifts.",
    { featured: true, personalizationEnabled: true, tags: ["maasai", "embroidery", "corporate"] }),
  p("eco-friendly-tech-gift-sets", "Branded Eco-Friendly Tech Gift Set", 4000, 4500,
    ["corporate-gifts-kenya", "power-banks", "corporate-gift-sets", "executive-corporate-gifts"],
    "A recycled-material tech set — power bank, cable and notebook.",
    "An eco-friendly tech gift set built from recycled materials: a 10,000mAh power bank, a braided cable set, a recycled-paper notebook and a tote, all in recycled packaging.",
    { tags: ["tech", "eco", "corporate"] }),
  p("3-piece-corporate-gift-set", "Personalized 3-Piece Executive Gift Set", 4000, 4500,
    ["corporate-gifts-kenya", "corporate-gift-sets", "executive-corporate-gifts", "branded-executive-pens"],
    "Three executive pieces, branded and boxed.",
    "A three-piece executive set — a metal pen, an A5 diary and a leather card holder — branded to your specification and presented in a gift box.",
    { tags: ["corporate", "set"] }),
  p("premium-personalized-3-piece-executive-gift-set-2", "Premium Personalized 3-Piece Executive Gift Set", 4000, 4500,
    ["corporate-gifts-kenya", "corporate-gift-sets", "executive-corporate-gifts"],
    "Our premium three-piece executive set.",
    "A premium three-piece executive gift set with a leather folder, a metal pen and a card holder, all monogrammed and boxed with a handwritten card.",
    { personalizationEnabled: true, tags: ["corporate", "premium", "set"] }),
  p("personalized-executive-engineer-gift-set", "Personalized Executive Engineer Gift Set", 4999, 5500,
    ["corporate-gifts-kenya", "corporate-gift-sets", "executive-corporate-gifts", "power-banks"],
    "Built for engineers — tools that get used every day.",
    "A gift set chosen for engineers: a power bank, a multi-tool card, a quality notebook and a laser-etched key tag, branded and boxed.",
    { tags: ["corporate", "engineer", "set"] }),
  p("custom-branded-bamboo-desk-organizer-with-wireless-phone-charger-pen-holder", "Custom Branded Bamboo Desk Organizer with Wireless Phone Charger & Pen Holder", 4299, 5500,
    ["desk-organizers-in-nairobi", "corporate-gifts-kenya", "promotional-gifts", "wooden-products"],
    "A bamboo desk organizer with a built-in wireless charger.",
    "A bamboo desktop organizer with a wireless charging pad, a pen holder and a phone slot, laser-etched with your logo. A gift that sits on the desk and keeps working.",
    { tags: ["desk", "bamboo", "tech", "wireless"] }),
  p("reusable-corporate-promotional-bottles", "Reusable Corporate & Promotional Bottles", 1499, 2000,
    ["promotional-gifts", "water-bottles", "corporate-gifts-kenya"],
    "Reusable printed bottles for events and teams.",
    "Reusable bottles in a range of shapes and finishes, printed with your logo for events, conferences and staff gifting. Bulk pricing applies from 24 units.",
    { tags: ["bottle", "corporate", "bulk"] }),
  p("personalized-rose-gold-spinning-pendant-necklace", "Personalized Rose Gold Spinning Pendant Necklace", 1999, 2500,
    ["pendant-necklaces", "personalized-gifts", "for-her", "couple-necklaces"],
    "A spinning pendant necklace in rose gold, engraved free.",
    "A rose gold spinner pendant on a fine chain, with the circle engraved and the centre stone set to rotate. Comes in a presentation box ready to give.",
    { featured: true, personalizationEnabled: true, tags: ["necklace", "rose-gold", "personalized"] }),
  p("personalized-football-fan-thermal-water-bottle-500ml", "Personalized Football Fan Thermal Water Bottle – 500ml", 1799, 2000,
    ["promotional-gifts", "water-bottles", "personalized-gifts", "for-him"],
    "A 500ml thermal bottle for the football fan in your life.",
    "A thermal bottle printed with a team name, a squad number or a player's name. Popular for birthdays, tournament weekends and end-of-season gifts.",
    { personalizationEnabled: true, tags: ["bottle", "football", "personalized"] }),
  p("personalized-ladies-pink-4-in-1-gift-set", "Personalized Ladies Pink 4-in-1 Gift Set", 3799, 4500,
    ["ladies-gifts", "ladies-giftsets", "corporate-gifts-kenya", "for-her"],
    "Four pieces in pink, boxed and personalised.",
    "A four-in-one gift set in a soft pink palette — a tumbler, a notebook, a keychain and a tote bag, each printed with a name or message and boxed together.",
    { personalizationEnabled: true, tags: ["set", "ladies", "pink", "personalized"] }),
  p("custom-branded-metallic-sports-water-bottle-750ml", "Custom Branded Metallic Sports Water Bottle – 750ml", 1499, 2000,
    ["promotional-gifts", "water-bottles", "corporate-gifts-kenya", "personalized-gifts"],
    "A 750ml metallic sports bottle with a branded print.",
    "A large-capacity metallic sports bottle with a secure lid and a carry loop, printed with your logo. A giveaway that gets used at the gym, not binned.",
    { tags: ["bottle", "metallic", "sports"] }),
  p("personalized-eco-friendly-corporate-gift-set", "Personalized Eco-Friendly Corporate Gift Set", 4999, 5500,
    ["corporate-gifts-kenya", "corporate-gift-sets", "power-banks", "executive-corporate-gifts"],
    "A recycled and reusable corporate gift set.",
    "An eco-friendly corporate set made from recycled and responsibly sourced materials, personalised with your logo and packed in recycled card with no plastic.",
    { tags: ["corporate", "eco", "personalized"] }),
  p("personalized-bamboo-spiral-notebook-pen-set", "Personalized Bamboo Spiral Notebook & Pen Set", 1999, 2500,
    ["promotional-gifts", "customized-notebooks", "corporate-gifts-kenya", "personalized-gifts"],
    "A bamboo-cover notebook and pen, laser-etched together.",
    "A160-page notebook with a bamboo cover and metal spiral binding, paired with a matching bamboo pen. Both laser-etched with a name or logo.",
    { personalizationEnabled: true, tags: ["notebook", "bamboo", "personalized"] }),
  p("mann-filter-premium-corporate-gift-set", "MANN FILTER Premium Corporate Gift Set", 10499, 12000,
    ["corporate-gifts-kenya", "corporate-gift-sets", "executive-corporate-gifts", "keychains"],
    "Our premium corporate hamper — the one people photograph.",
    "Our highest-value corporate gift: a premium gift set with an engraved key tag, an executive diary, a metal pen, a leather card holder and a travel tumbler, in a rigid presentation box.",
    { featured: true, tags: ["corporate", "premium", "hamper"] }),
  p("personalized-premium-leather-wallet", "Personalized Premium Leather Wallet", 2000, 2500,
    ["promotional-gifts", "leather-wallets", "personalized-gifts", "for-him"],
    "A premium leather wallet, monogrammed at no extra charge.",
    "A full-grain leather wallet with a clean card layout, monogrammed with initials or a short message on the inner panel and supplied in a gift box.",
    { personalizationEnabled: true, tags: ["wallet", "leather", "personalized"] }),
  p("premium-brown-leather-bifold-wallet", "Premium Brown Leather Bifold Wallet", 2000, 2500,
    ["promotional-gifts", "leather-wallets", "men-gifts", "mens-leather-wallets"],
    "A warm brown leather bifold with a note pocket.",
    "A brown leather bifold with six card slots, a note compartment and a full-grain finish that darkens beautifully with use.",
    { tags: ["wallet", "brown", "leather"] }),
  p("mens-black-leather-bifold-wallet", "Men's Personalized Black Leather Bifold Wallet", 2000, 2500,
    ["promotional-gifts", "leather-wallets", "men-gifts", "personalized-gifts"],
    "A black leather bifold with free monogramming.",
    "A black leather bifold with RFID-blocking card slots and a full inner monogram panel. Supplied in a gift box with a card.",
    { personalizationEnabled: true, tags: ["wallet", "black", "personalized"] }),
  p("eco-friendly-corporate-gifts-2", "Branded A3 Jute Tote Bag & 500ml Tea Separation Mug Gift Set", 3799, 4500,
    ["corporate-gifts-kenya", "jute-tote-bags", "corporate-gift-sets", "thermo-mugs"],
    "An A3 tote and a tea-separation mug, branded and boxed.",
    "A reusable A3 jute tote paired with a 500ml tea-separation stainless mug, both branded and presented in a gift box. A thoughtful set for staff or clients.",
    { tags: ["set", "jute", "mug", "corporate"] }),
  p("maasai-fleece-blankets-at-rio-gift-shop", "Branded Yellow Maasai-Inspired Fleece Blanket", 3499, 4000,
    ["maasai-blankets-in-nairobi", "kenya-inspired-blankets", "corporate-gifts-kenya"],
    "A yellow Maasai-inspired fleece blanket with a branded panel.",
    "A warm yellow Maasai-inspired fleece blanket with a reinforced hem and a printable panel for your logo. One of the most popular corporate gifts we sell.",
    { featured: true, personalizationEnabled: true, tags: ["maasai", "blanket", "yellow"] }),

  // ---------- Mega-menu featured products ----------
  p("rio-gift-shop-watches-in-kenya", "CRRJU Men's Business Stainless Steel Wrist Watch", 3800, undefined,
    ["men-watches-on-sale", "mens-watches", "crrju", "men-gifts", "for-him"],
    "A stainless steel business watch with a clean, dress-ready face.",
    "A stainless steel case with a brushed finish, a date window and a slim profile that sits well under a cuff. Japanese quartz movement with a two-year battery and a leather-look strap.",
    { tags: ["watch", "men", "stainless"] }),
  p("gold-stainless-steel-bracelets", "Personalized Gold Stainless Steel Bracelet", 1999, 2500,
    ["kenya-bracelets", "bracelets-for-women", "personalized-gifts", "for-her"],
    "A gold stainless steel bracelet, engraved free.",
    "A polished gold-tone stainless steel bracelet with an adjustable clasp. Engrave a name, a date or a short message on the inner face and it ships in a gift box.",
    { featured: true, personalizationEnabled: true, tags: ["bracelet", "gold", "personalized"] }),
  p("branded-notebooks-in-nairobi", "Branded A5 Notebook", 1349, 1500,
    ["promotional-gifts", "customized-notebooks", "corporate-gifts-kenya", "personalized-gifts"],
    "An A5 notebook with a printed cover, available in a range of colours.",
    "A hardback A5 notebook with a lay-flat binding, 160 pages and a printed full-cover logo. Available in six colours, with bulk pricing from 25 units.",
    { featured: true, tags: ["notebook", "branded", "a5"] }),
  p("crystal-awards-at-rio-gift-shop", "Round Moon Crystal Awards with Wooden Base", 7499, 8000,
    ["corporate-gifts-kenya", "companies-awards", "crystal-items", "individuals-awards", "schools-awards"],
    "A round crystal award on a wooden base, engraved and ready to present.",
    "Optical crystal cut into a round moon form on a solid wooden base. We laser-engrave the recipient's name, the achievement and the year. Also available in square and flame designs.",
    { featured: true, tags: ["trophy", "crystal", "award"] }),
  p("stanley-style-pink-mug", "Personalized Pink Stanley-Inspired Tumbler", 2499, 3000,
    ["personalized-gifts", "stanley-inspired-cups", "tumbler", "corporate-gifts-kenya", "for-her"],
    "A pink insulated tumbler in the classic handled style, printed with a name.",
    "A 500ml double-walled tumbler in a soft pink with a carry handle and a matching straw lid. Printed with a name, an initial or a short message — a gift that gets carried everywhere.",
    { featured: true, personalizationEnabled: true, tags: ["tumbler", "pink", "personalized"] }),
  p("personalized-spinner-pendant-necklace", "Personalized Spinner Pendant Necklace", 1999, undefined,
    ["pendant-necklaces", "pendant-necklaces", "personalized-gifts", "for-her", "couple-necklaces"],
    "A spinner pendant in silver with a free engraving.",
    "A sterling-look spinner pendant on a 45cm chain, with a rotating centre and a free engraving on the outer ring. Supplied in a gift box.",
    { tags: ["necklace", "spinner", "personalized"] }),
  p("personalized-spinner-pendant-necklace-2", "Personalized Spinner Pendant Necklace", 1999, undefined,
    ["pendant-necklaces", "pendant-necklaces", "personalized-gifts", "valentines-necklaces"],
    "Our second spinner pendant design, with a cut-out centre.",
    "A second spinner pendant design with a cut-out centre stone that catches the light as it turns. Free engraving, chain included, boxed ready to give.",
    { tags: ["necklace", "spinner", "valentines"] }),
];
